services:
  app:
    build: .
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/gaylistesi
      PORT: 3000
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:

volumes:
  postgres_data:
